name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.me
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.me
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: Analyze Test and/or Coverage Results
      if: always()
      uses: thundra-io/foresight-test-kit-action@v1
      with:
        api_key: ${{ secrets.foresight_api_key }}
        test_path: ./junit.xml
